# accès SMTP
SMTP_HOST = "smtp.office365.com"
SMTP_PORT = "587"
SENDER_NAME = "Romane FOURRIER"
SENDER_EMAIL = "prenom.nom@votre-entreprise.com"
SENDER_PASSWORD = "votre_mot_de_passe_smtp"

# autres paramètres
DEFAULT_LANGUAGE = "FR"
SUBJECT_FR = "Suivi commandes en cours"
SUBJECT_EN = "Follow-up on ongoing orders"
